---
- name : Setup Application Environment
  hosts: webserver
  remote_user: ansible
  become: True
  tasks:
    - name : Install Git
      apt:
        name: git
        state: present
        update_cache: yes

    - name : Install python pip3
      apt:
        name: python3-pip
        state: present
        update_cache: yes
    
    - name : Install tmux
      apt:
        name: tmux
        state: present
        update_cache: yes

    - name : Install htop
      apt:
        name: htop
        state: present
        update_cache: yes

    - name : Install Flask
      pip:
        name: flask
        executable: pip3
      
    - name: install flask requests
      pip: 
        name: requests
        executable: pip3


    - name: install flask_SQLAlchemy
      pip: 
        name : Flask_SQLAlchemy
        executable: pip3


    - name: install python-dotenv
      pip: 
        name : python-dotenv
        executable: pip3
        

    - name: Clone a Web App repo
      ansible.builtin.git:
        repo: https://github.com/siddhartha-12/Weather-App.git
        dest: /var/flask-app

    - name: Copy service file to systemd
      ansible.builtin.copy:
        remote_src: yes
        src: /var/flask-app/flask/flaskapp.service
        dest: /etc/systemd/system/flaskapp.service
        mode: '0644'
    
    - name: Reload service reload
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: yes
        name: flaskapp.service
    
    - name: Enable flaskapp.service
      ansible.builtin.systemd:
        name: flaskapp.service
        state: started
        enabled: yes
    
    - name: Make sure a service flaskapp.service is running
      ansible.builtin.systemd:
        state: started
        name: flaskapp.service

    # - name: Start Flask
    #   shell: "flask run"
    #   environment:
    #     FLASK_APP: /var/flask-app/flask/app.py