---
- name : Setup Application Environment
  hosts: localhost
  connection: local 
  become: True
  tasks:
    - name : Updating OS
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name : Upgrading OS
      apt: upgrade=dist force_apt_get=yes

    - name : Install Git
      apt:
        name: git
        state: present
        update_cache: yes

    - name : Install python pip3
      apt:
        name: python3-pip
        state: present
        update_cache: yes
    
    - name : Install tmux
      apt:
        name: tmux
        state: present
        update_cache: yes

    - name : Install htop
      apt:
        name: htop
        state: present
        update_cache: yes

    - name : Install NPM
      apt:
        name: npm
        state: present
        update_cache: yes

    - name : Install Flask
      pip:
        name: flask
        executable: pip3
      
    - name: install flask requests
      pip: 
        name: requests
        executable: pip3

    - name: install flask_SQLAlchemy
      pip: 
        name : Flask_SQLAlchemy
        executable: pip3

    - name: install python-dotenv
      pip: 
        name : python-dotenv
        executable: pip3     

    - name: Clone a Web App repo
      ansible.builtin.git:
        repo: https://github.com/siddhartha-12/Weather-App.git
        dest: /var/flask-app

    - name: Copy service file to systemd
      ansible.builtin.copy:
        remote_src: yes
        src: /var/flask-app/flask/flaskapp.service
        dest: /etc/systemd/system/flaskapp.service
        mode: '0644'

    - name: Reload service reload
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: yes
        name: flaskapp.service

    - name: Starting flaskapp service
      ansible.builtin.systemd:
        name: flaskapp.service
        state: started
        enabled: yes