Vagrant.configure("2") do |config|
  # Use the same key for each machine
  config.ssh.insert_key = false
  config.vm.define "webserver" do |subconfig|
    subconfig.vm.box = "ubuntu/trusty64"
    subconfig.vm.hostname = "Web-Server"
    subconfig.vm.network "private_network", ip: "192.168.50.4"
    subconfig.vm.network "forwarded_port", guest: 80, host: 8080
    subconfig.vm.network "forwarded_port", guest: 443, host: 8443
  end
end
